export const regiones = {'I':  "de Tarapacá",
'II':  "Región de Antofagasta",
'III': "Región de Atacama",
'IV': "Región de Coquimbo",
'V': "Región de Valparaíso",
'VI': "Región del Libertador General Bernardo O\'Higgins",
'VII': "Región del Maule",
'VIII': "Región de Concepción",
'IX': "Región de la Araucanía",
'X': "Región de Los Lagos",
'XI': "Región de Aysén del General Carlos Ibañez del Campo",
'XII': "Región de Magallanes y de la Antártica Chilena",
'RM': "Región de Metropolitana de Santiago",
'XIV': "Región de Los Ríos",
'XV': "Región de Arica y Parinacota",
'XVI': "Región del Ñuble"}